// <auto-generated />
namespace DataVis.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addedhidedwidgets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedhidedwidgets));
        
        string IMigrationMetadata.Id
        {
            get { return "201605151246219_added hided widgets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
